name: CD starter a completer

on:
  workflow_dispatch:

jobs:
  consigne:
    runs-on: ubuntu-latest
    steps:
      - name: Consigne
        run: |
          echo "Ce workflow est volontairement minimal."
          echo "Les etudiants doivent ajouter staging, production simulee, smoke test et rollback."
